#+TITLE: My Personal Notes on NLP with Python
#+AUTHOR: Kholid Fuadi, SE., MSi
#+DATE: <2016-11-17 Thu>
#+STARTUP: indent

* Pendahuluan
Menurut wikipedia, Pemrosesan Bahasa Alami (PBA) atau NLP (Natural
Language Processing), adalah cabang ilmu komputer dan linguistik yang
mengkaji interaksi antara komputer dengan bahasa (alami)
manusia.[fn:1]

Secara sederhana, saya menterjemahkan NLP sebagai disiplin ilmu yang
berusaha untuk mempelajari bahasa manusia. Seperti diketahui bahasa
manusia sangat kompleks, namun bukan berarti tidak dapat dipahami oleh
komputer sama sekali. Dengan menggunakan analisis bentuk dan pola,
mesin yang sudah terlatih dapat mengetahui apa maksud yang terkandung
dalam sebuah teks.

Inilah yang menjadi tujuan dari NLP, membuat mesin memahami maksud
dari teks yang ditulis maupun diucapkan manusia. Anda bisa bayangkan
jika mesin dapat berinteraksi dengan manusia? Ya, kurang lebih seperti
si Jarvis dalam film Iron Man. Bahasa manusia yang diterima oleh
komputer perlu diproses dahulu supaya komputer dapat memahami maksud
dari bahasa manusia.

Sebelum sampai ke materi yang sulit, saya ingin mulai belajar NLP dari
hal-hal yang sederhana dahulu.

** Aplikasi NLP[fn:2]
- Mesin penjawab pertanyaan otomatis
- Program pengategorian dokumen otomatis
- Text mining
- Mesin translasi
- Program pembelajaran bahasa
- Spelling correction
- Plagiarism detection
- Speech recognition
- Text to speech

** Kendala NLP
- Bahasa = kata + aturan + pengecualian
- Bahasa alami mengandung ambiguitas
- Bahasa manusia tidak hanya satu
- Bahasa manusia terus berubah

** Bahasa dapat dibagi menjadi 2 macam
- Bahasa alami, misal bahasa indonesia, jawa, inggris
- Bahasa buatan, misal bahasa pemrograman komputer, bahasa pemodelan

* Rumusan Masalah
Batasan rumusan masalah dalam /paper/ ini adalah dalam konteks bahasa
Indonesia, karena memang belum banyak penelitian maupun /dataset/
dalam bahasa Indonesia.


* Metode
** Sumber Data
- Twitter
- Kaskus
- Facebook
* Analisis
** Analisis Sentimen
Apakah teks bermakna *positif*, *negatif* atau *netral*? Sumber teks
bisa dari kalimat, tweet, pesan SMS, review konsumen, dokumen, dan
seterusnya.
* Kesimpulan
* Daftar Pustaka
- [ ] Natural Language Processing (almost) from Scratch,
  https://arxiv.org/pdf/1103.0398v1.pdf
- [ ] Kumpulan video PBA di youtube,
  https://www.youtube.com/results?search_query=pemrosesan+bahasa+alami
* Footnotes

[fn:1] [[https://id.wikipedia.org/wiki/Pemrosesan_bahasa_alami][Pemrosesan Bahasa Alami {wikipedia}]]

[fn:2] https://youtu.be/nSzrOl_vnn4?t=61
